name: Custom Enchantment Suggestions
description: Suggest a Custom Enchantment idea for MineInAbyss
labels: [suggestion:enchantment]
body:
  - type: input
    attributes:
      label: Enchantment name
      description: What is the name of the enchantment?
      placeholder: Soulbound
    validations:
      required: true

  - type: textarea
    attributes:
      label: Enchantment Info
      description: |
        Please add a description and general information about the enchantment below.
        Effect, level-tiers etc..
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Obtainability
      description: How would the enchantment be obtained?
      options:
        - label: Enchanted Books
        - label: Enchantment Table (Randomly applied)
        - label: Vendor Trades
        - label: Dungeon Loot
        - label: Other (Details in Additional Info)

  - type: textarea
    attributes:
      label: Additional info
      description: |
        If you feel like additional information would be helpful add it here.
        Could be wiki-pages or something not fitting in any of the boxes above.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open suggestion similar to this.
          required: true
        - label: I have ensured the mob I'm suggesting isn't already on the server.
          required: true