name: Relic Suggestion
description: Suggest a relic idea for MineInAbyss
labels: ["status:undecided", "suggestion:relic"]
body:
  - type: input
    attributes:
      label: Relicname
      description: What is the name of the relic?
      placeholder: Scaled Umbrella
    validations:
      required: true

  - type: input
    attributes:
      label: Relic Location
      description: Where would the relic be found?
      placeholder: Layer 1 / Craftable via recipe.
    validations:
      required: true

  - type: dropdown
    id: relicTier
    attributes:
      label: Relic Tier
      description: |
        What tier is this relic in?
        Would detail the rarity of said relic.
      options:
        - Special Grade
        - First Grade
        - Second Grade
        - Third Grade
        - Fourth Grade

  - type: textarea
    attributes:
      label: Relic Info
      description: |
        Please add a description and general information about the relic below.
        For example ability, functionality, amount of uses or durability etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relic Model/Texture
      description: |
        Do you have a custom texture/model? If so you can drop an image/file below.
        If not, please provide some form of description via either images or text.
    validations:
      required: true

  - type: input
    attributes:
      label: Related recipe ideas
      description: |
        Are there any suggested recipes related to this relic?
        If so mention them with '#ISSUE_NUMBER' below
      placeholder: '#10 and #12'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info
      description: |
        If you feel like additional information would be helpful add it here.
        Could be wiki-pages or something not fitting in any of the boxes above.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open suggestion similar to this.
          required: true
        - label: I have ensured the relic I'm suggesting isn't already on the server.
          required: true