name: Stonecutter Recipe Suggestion
description: Suggest a stonecutter recipe idea
labels: ["status:undecided", "suggestion:recipe"]
body:
  - type: input
    attributes:
      label: Input Item
      description: What item is used as the input?
      placeholder: Blackstone
    validations:
      required: true

  - type: input
    attributes:
      label: Group / Tag
      description: |
        What group of blocks/items does this recipe return?
        Groups are defined within each items file, but it does also support vanilla options like 'planks'
      placeholder: looty:blackstone
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: If you feel like additional information would be helpful add it here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
        - label: I have ensured the recipe I'm requesting isn't already in the server.
          required: true

