name: Suggest General Item
description: Suggest an item idea for MineInAbyss
labels: ["status:undecided", "suggestion:item"]
body:
  - type: dropdown
    id: itemType
    attributes:
      label: Item Type
      description: What type of item is this?
      options:
        - Tool
        - Weapon
        - Armor
        - Equipment
        - Material
        - Other

  - type: input
    attributes:
      label: Item name
      description: What is the name of the item?
      placeholder: Cave Raider Helmet
    validations:
      required: true

  - type: textarea
    attributes:
      label: Item Info
      description: |
        Please add a description and general information about the item below.
        For example ability, functionality, amount of uses or durability etc.
      placeholder: Used to light up dark caves when exploring.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Item Model/Texture
      description: |
        Do you have a custom texture/model? If so you can drop an image/file below.
        If not, please provide some form of description via either images or text.
    validations:
      required: true

  - type: input
    attributes:
      label: Obtainability
      description: How would the item be found?
      placeholder: Craftable via recipe / Bought from Orth Merchants.
    validations:
      required: true

  - type: input
    attributes:
      label: Related recipe ideas
      description: |
        Are there any suggested recipes related to this item?
        If so mention them with '#ISSUE_NUMBER' below
      placeholder: '#10 and #12'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info
      description: |
        If you feel like additional information would be helpful add it here.
        Could be wiki-pages or something not fitting in any of the boxes above.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open suggestion similar to this.
          required: true
        - label: I have ensured the relic I'm suggesting isn't already on the server.
          required: true
